name: AntiVoid
main: BreathTakinglyBinary\AntiVoid\AntiVoid
version: 1.3.0
api: 5.0.0
load: POSTWORLD
author: FiberglassCivic
description: A simple plugin to save players from falling into the void.
website: https://github.com/BreathTakinglyBinary/AntiVoid